add_library(unirally_sampling STATIC track_sampling.cpp track_progress.cpp)
target_include_directories(unirally_sampling PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(unirally_sampling PUBLIC lab_options)

add_library(unirally_speed_limits STATIC speed_limits.cpp)
target_include_directories(unirally_speed_limits PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(unirally_speed_limits PUBLIC lab_options)
